### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-singleton-bect-chambouvet-singleton#1]
Hello,

- [ ] J'aimerai bien un exemple alors 
> Peut-on surcharger une méthode static ? 
On peut surcharger une méthode statique à condition de spécifier le mot-clé static.

- [ ] Faux 
> À quoi fait référence name="logger" dans la property ?
Cet attribut spécifie l'identifiant unique du bean.

- [ ] ⚠️ Le rapport est un peu tout péter et non terminé, notamment sur la définition de ce qu'est l'autowiring

- [ ] TP pas terminé

**Comment by corentin521** [comment]
Bonjour  @Slashgear  ,

Nous avons rajouté un exemple de surcharge de méthode static dans le rapport et modifié nos réponses concernant les property des bean ainsi que l'autowiring . Nous avons également ajouté un projet singleton-spring-boot qui n'utilise que des annotations et le fichier application.properties.

Merci pour ce retour. 

Bonne journée !

**Comment by Slashgear** [comment]
- Alors je vois le souci, on a pas la même définition de la surcharge. Quand j'entends surcharge, j'entends `Override` Et non on ne peut pas Override une method static.

Sinon la partie SpringBoot c'est top. J'espère que maintenant, vous avez une meilleur idée de ce qu'est Spring.
